version: "3.7"
services:
  php:
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=storybook
      PHP_XDEBUG_CLIENT_HOST: host.docker.internal # Docker 18.03+ Mac/Win
      PHP_XDEBUG_LOG: /tmp/php-xdebug.log
      PHP_XDEBUG_START_WITH_REQUEST: "true"
